name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

env:
  IMAGE_NAME: triton-cpu-onnxruntime-r23_12

jobs:
  image:
    name: Build Image And Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        shell: 'script -q -e -c "bash {0}"'
        run: |
          wget -c https://github.com/triton-inference-server/server/archive/refs/tags/v2.41.0.zip
          unzip v2.41.0.zip
          cd server-2.41.0
          python build.py --enable-logging --endpoint=grpc --endpoint=http --repo-tag=common:r23.12 --repo-tag=core:r23.12 --repo-tag=backend:r23.12 --repo-tag=thirdparty:r23.12 --backend=onnxruntime:r23.12
          docker images
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=${{ github.run_number }}
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
